spring.application.name=event-service

server.port=8084

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticket_booking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt configuration
jwt.secret=9380a2b67ee9cc28f074988a2e378c9c5918e6dd68f9751b432e54de5b7ecf0c