spring.application.name=event-service

server.port=8082

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticket_booking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt configuration
jwt.secret=169231adeb876d9a1a3bd188dfc0641b54f63594639205b5fc844bd8656f57c8
