spring.application.name=user-service

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticket_booking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration (HS256)
jwt.secret=mySecretKey123456789
jwt.expiration-ms=1800000

# 30-minute inactivity timeout for CUSTOMER role
security.customer.inactivity-timeout-minutes=30